model:
  architecture: "3D_DenseNet"

data:
  path: "../data"
  num_classes: 3
  train_val_split: 0.8

training:
  epochs: 10 # change to 20 if all batch size, growth_rate, num_layers are final
  batch_size: 2
  shuffle: True
  pin_memory: True
  mixed_precision: True

validation:
  batch_size: 2
  shuffle: False
  pin_memory: True

optimizer:
  name: adam
  lr: 0.0001
  weight_decay: 0

loss:
  name: crossentropyloss

feature_block:
  in_channels: 1
  growth_rate: 16 # can change to 64 if GPU can handle it use either 32 or 16 only
  num_layers: 4
  activation: "Relu"
  normalization: "batch_norm"