model:
  architecture: "3D_DenseNet"

data:
  path: "../data"
  num_classes: 3
  train_val_split: 0.8

training:
  epochs: 200
  batch_size: 2
  shuffle: True
  pin_memory: True
  mixed_precision: True
  early_stop:
    patience: 5
    min_delta: 0.01

validation:
  batch_size: 2
  shuffle: False
  pin_memory: True

optimizer:
  name: adamw
  lr: 0.0005
  weight_decay: 0.01
  momentum: 0.9

loss:
  name: crossentropyloss
  label_smoothing: 0.1

feature_block:
  in_channels: 1
  growth_rate: 12
  use_transition: True
  compression: 0.75
  dense_block:
    blocks: 1
    layers: 4