model:
  architecture: "3D_DenseNet"

data:
  path: "../data"
  num_classes: 3
  train_val_split: 0.8

training:
  epochs: 100
  batch_size: 1
  shuffle: True
  pin_memory: True
  mixed_precision: True
  early_stop:
    patience: 5
    min_delta: 0.01
  weights: [1.0, 6.0, 3.0]

validation:
  batch_size: 1
  shuffle: False
  pin_memory: True

optimizer:
  name: adam
  lr: 0.0005
  weight_decay: 0 # 0.0001
  momentum: 0.9

loss:
  name: crossentropyloss

feature_block:
  in_channels: 1
  growth_rate: 24
  use_transition: False
  compression: 0.5
  dense_block:
    blocks: 1
    layers: 5